import { playwright } from "@vitest/browser-playwright";
import { defineConfig } from "vitest/config";

export default defineConfig({
	optimizeDeps: {
		include: [
			"react",
			"react/jsx-dev-runtime",
			"react/jsx-runtime",
			"react-dom",
			"react-dom/client",
			"koota",
			"clsx",
			"tailwind-merge",
			"yuka",
			"reactylon",
			"reactylon/web",
			"@babylonjs/core/Cameras/arcRotateCamera",
			"@babylonjs/core/Animations/animation",
			"@babylonjs/core/Engines/engine",
			"@babylonjs/core/Engines/shaderStore",
			"@babylonjs/core/Events/pointerEvents",
			"@babylonjs/core/Loading/sceneLoader",
			"@babylonjs/core/Materials/PBR/pbrMaterial",
			"@babylonjs/core/Materials/shaderLanguage",
			"@babylonjs/core/Materials/Textures/texture",
			"@babylonjs/core/Materials/standardMaterial",
			"@babylonjs/core/Maths/math.color",
			"@babylonjs/core/Maths/math.vector",
			"@babylonjs/core/Meshes/Builders/cylinderBuilder",
			"@babylonjs/core/Meshes/Builders/planeBuilder",
			"@babylonjs/core/Meshes/Builders/sphereBuilder",
			"@babylonjs/core/Meshes/Builders/torusBuilder",
			"@babylonjs/core/Meshes/meshBuilder",
			"@babylonjs/core/Misc/screenshotTools",
			"@babylonjs/core/Misc/tools",
			"@babylonjs/core/scene",
			"@babylonjs/loaders/glTF",
			"tone",
			"sql.js/dist/sql-asm.js",
		],
	},
	test: {
		browser: {
			enabled: true,
			provider: playwright(),
			headless: false,
			instances: [{ browser: "chromium" }],
		},
		include: ["tests/components/**/*.browser.test.tsx"],
	},
});
