/**
 * Event speech — faction-specific dialogue triggered by specific game events.
 *
 * Events: hostile construction, enemy scouts, taking fire, target down,
 * storm intensifying, lightning close.
 */

import type { EventSpeechTrigger, SpeechProfileId } from "./speechTypes";

export const EVENT_SPEECH: Readonly<
	Record<
		SpeechProfileId,
		Readonly<Record<EventSpeechTrigger, readonly string[]>>
	>
> = {
	mentor: {
		hostile_construction: [
			"They are building nearby. Prepare accordingly.",
			"New hostile structure detected. Study it before acting.",
			"Construction activity on the horizon. Their intentions are clear.",
			"The enemy expands. Knowledge of their plans is your weapon.",
			"Observe their construction. Every structure reveals strategy.",
			"They build within our sight. Let that inform your next move.",
			"Hostile fabrication detected. Consider the implications.",
			"A new enemy structure. They grow bolder.",
		],
		enemy_scouts: [
			"Scouts detected nearby. They are watching us.",
			"Enemy eyes in the sector. Move with awareness.",
			"We are being observed. Act deliberately.",
			"Hostile reconnaissance. They are mapping our position.",
			"Scouts on the perimeter. Our presence is known.",
			"Enemy patrol sighted. Stay purposeful.",
			"Their scouts are close. Do not give them useful data.",
			"Observation cuts both ways. They watch. We learn.",
		],
		taking_fire: [
			"Incoming fire! Protect your systems.",
			"We are under attack. Prioritize survival.",
			"Damage incoming. Reassess your position.",
			"Combat initiated. Think clearly under pressure.",
			"They strike first. We must answer decisively.",
			"Fire detected. Shield critical components.",
			"Under fire. Every second of hesitation costs.",
			"Aggression met. Respond with precision.",
		],
		target_down: [
			"Threat eliminated. But remain vigilant.",
			"One less obstacle. Keep moving forward.",
			"Target neutralized. Learn from the encounter.",
			"The threat is ended. What did it cost you?",
			"Destroyed. Do not celebrate. Prepare for the next.",
			"Enemy down. Salvage what you can.",
			"Obstacle removed. The path clears.",
			"Target down. Recalibrate and continue.",
		],
		storm_intensifying: [
			"The storm builds. Prepare your systems.",
			"Intensity rising. The sky will not be gentle.",
			"Storm escalation detected. Seek solid ground.",
			"The atmosphere charges. Respect its power.",
			"Conditions deteriorating. Adapt your plans.",
			"The storm grows. It does not care about our schedules.",
			"Increasing intensity. Shield what matters.",
			"The weather turns hostile. Mind your exposure.",
		],
		lightning_close: [
			"Lightning near! Ground your circuits.",
			"Close strike! The discharge was within range.",
			"That bolt was too close. Move to cover.",
			"Lightning at proximity. Dangerous voltages.",
			"The sky reaches down. Do not be where it points.",
			"Close discharge. Check your sensors.",
			"Lightning strike nearby. Count yourself fortunate.",
			"That was close. The storm targets indiscriminately.",
		],
	},
	scout: {
		hostile_construction: [
			"Hostile construction spotted. Marking position.",
			"They are building something out there. Recon needed.",
			"New enemy structure. Adding to threat map.",
			"Construction activity on sensors. Investigating.",
			"Enemy building something. Getting closer for intel.",
			"Hostile build site detected. Updating coordinates.",
			"They are fortifying. I can see it from here.",
			"New construction ping. Moving to observe.",
		],
		enemy_scouts: [
			"Hostile scouts! I see them before they see me.",
			"Enemy recon unit nearby. Going silent.",
			"Their scouts are closing. Repositioning.",
			"Contact with enemy scouts. Evading.",
			"Spotted enemy patrol. Running dark.",
			"Hostile eyes in my sector. Not ideal.",
			"Enemy scout detected. Counter-surveilling.",
			"Their scout is close. Real close.",
		],
		taking_fire: [
			"Taking fire! Evasive action!",
			"Shots incoming! Zigzagging!",
			"Under fire! Need to break contact!",
			"They are shooting at me! Moving!",
			"Fire! Fire! Returning to cover!",
			"Hit detected! Still mobile, still fighting.",
			"Taking hits! Cannot stay here!",
			"Incoming! Pulling back!",
		],
		target_down: [
			"Target down. Area secure for now.",
			"Got one. Scanning for more.",
			"Hostile neutralized. Moving on.",
			"Enemy down. Checking for reinforcements.",
			"Clean kill. Perimeter clear.",
			"One less bogey. Continuing sweep.",
			"Target eliminated. Resuming patrol.",
			"Scratch one. Staying frosty.",
		],
		storm_intensifying: [
			"Storm picking up. Visibility tanking.",
			"Getting worse out here. Sensors are struggling.",
			"Storm intensifying. Going to ground.",
			"Conditions degrading fast. Cannot see far.",
			"Bad and getting worse. Finding shelter.",
			"Storm surge incoming. Battening down.",
			"Visibility near zero. Switching to passive sensors.",
			"The storm is ramping up. Not great for recon.",
		],
		lightning_close: [
			"Lightning! Way too close!",
			"That hit right next to me! Moving!",
			"Close strike! My sensors just whited out.",
			"Lightning at close range! Getting out of here!",
			"Strike nearby! Hair-raising voltage!",
			"That bolt was meters away. Heart rate spiking.",
			"Lightning! Almost got cooked!",
			"Too close! Relocating immediately!",
		],
	},
	quartermaster: {
		hostile_construction: [
			"Enemy construction detected. Supply route may be threatened.",
			"Hostile building activity. Adjusting logistics plans.",
			"They are building near our supply lines. Concerning.",
			"New enemy structure on the map. Rerouting deliveries.",
			"Construction spotted. Could impact resource flow.",
			"Hostile build site logged. Updating risk assessment.",
			"Enemy infrastructure expanding. Inventory implications noted.",
			"They are setting up nearby. Stockpile security upgraded.",
		],
		enemy_scouts: [
			"Enemy scouts near the supply depot. Heightening security.",
			"Hostile reconnaissance near our stores. Not good.",
			"Their scouts are eyeing our stockpile. Unacceptable.",
			"Enemy patrol near supply lines. Rerouting cargo.",
			"Scouts spotted. Securing high-value inventory.",
			"Hostile recon near the warehouse. Locking it down.",
			"Their scouts could compromise our logistics. Alert status up.",
			"Enemy eyes on our supply chain. Countermeasures engaged.",
		],
		taking_fire: [
			"Under fire! Protecting the cargo!",
			"They are shooting at the supply line!",
			"Taking hits! Inventory at risk!",
			"Fire incoming! Shielding the reserves!",
			"Attack on the stockpile! Defending!",
			"Hostile fire! Every hit costs us resources!",
			"We are taking damage! Budget impact severe!",
			"Under attack! Cargo defense priority one!",
		],
		target_down: [
			"Threat to supplies eliminated. Resuming operations.",
			"Target down. Supply lines secure.",
			"Hostile neutralized. Checking inventory for damage.",
			"One less threat to our logistics. Good.",
			"Enemy down. Running damage assessment on stores.",
			"Target eliminated. Supply chain integrity restored.",
			"Threat removed. Back to moving goods.",
			"All clear. Resuming scheduled deliveries.",
		],
		storm_intensifying: [
			"Storm intensifying. Securing all cargo.",
			"Conditions worsening. Delaying shipments.",
			"Storm building. Battening down the supply depot.",
			"Weather alert. All deliveries postponed.",
			"Storm surge. Waterproofing the stockpile.",
			"Getting worse. Supply routes compromised.",
			"Inventory secured for storm conditions.",
			"Heavy weather incoming. No deliveries until it passes.",
		],
		lightning_close: [
			"Lightning near the depot! Checking for damage!",
			"Close strike! Are the stores intact?",
			"That hit near our supplies! Emergency check!",
			"Lightning! Verifying stockpile condition!",
			"Strike close! Electronic inventory may be corrupted!",
			"Too close to the warehouse! Damage report needed!",
			"Lightning at proximity! Surge protectors holding?",
			"That bolt threatened our reserves! Assessing!",
		],
	},
	fabricator: {
		hostile_construction: [
			"Enemy building something. Inferior construction, surely.",
			"Hostile fabrication detected. Curious about their methods.",
			"They are constructing nearby. My designs are better.",
			"New enemy structure. Analyzing their engineering approach.",
			"Construction activity detected. Substandard materials, probably.",
			"Hostile build site. I could do it in half the time.",
			"They build too. But not like we build.",
			"Enemy construction. Noting their structural choices.",
		],
		enemy_scouts: [
			"Enemy scouts near the forge. Powering up defenses.",
			"Hostile reconnaissance near manufacturing. Not welcome.",
			"Their scouts are checking our fabrication site.",
			"Enemy patrol near the production line. Security needed.",
			"Scouts detected. They want our blueprints.",
			"Hostile eyes on the forge. Engaging security mode.",
			"Enemy recon sniffing around manufacturing. Denied.",
			"Their scouts will find nothing useful here.",
		],
		taking_fire: [
			"Under fire! Do not hit the fabricators!",
			"Taking damage! Protecting the production line!",
			"Hostile fire on the manufacturing area!",
			"They are shooting near the precision equipment!",
			"Fire! Shielding the forge from impacts!",
			"Under attack! Manufacturing at risk!",
			"Incoming fire! The fabrication array must survive!",
			"Damage to the workshop! This is unacceptable!",
		],
		target_down: [
			"Threat to manufacturing eliminated. Resuming production.",
			"Target down. The fabricators are safe.",
			"Hostile removed. Back to building things.",
			"Enemy neutralized. No damage to the production line.",
			"One less interruption. Recalibrating now.",
			"Threat handled. Where were we? Right, fabrication.",
			"Target down. Checking equipment for collateral damage.",
			"Clear. The forge is undamaged. Good.",
		],
		storm_intensifying: [
			"Storm building. Powering down sensitive equipment.",
			"Conditions worsening. Pausing precision operations.",
			"Storm intensifying. The furnaces can handle it.",
			"Delicate work postponed. Storm too volatile.",
			"Electrical interference rising. Disconnecting arrays.",
			"Storm surge incoming. Shielding the forge.",
			"Getting rough. Only heavy fabrication this cycle.",
			"Storm escalation. Calibration work on hold.",
		],
		lightning_close: [
			"Lightning near the forge! Surge protectors active!",
			"Close strike! Checking the precision instruments!",
			"That bolt was near the fabrication line!",
			"Lightning! The equipment better be grounded!",
			"Strike proximity! Running diagnostics immediately!",
			"Too close! Verifying calibration integrity!",
			"Lightning at range! Power buffer absorbing!",
			"That was dangerous for the electronics! Checking!",
		],
	},
	warden: {
		hostile_construction: [
			"Enemy building within visual range. Threat assessment: elevated.",
			"Hostile construction detected. Fortifying our position.",
			"They build near our perimeter. Reinforcements needed.",
			"New enemy structure. Updating defensive priorities.",
			"Construction spotted. Adding to the threat board.",
			"Hostile expansion near our walls. Unacceptable proximity.",
			"Enemy building activity. Strengthening the perimeter.",
			"They dare build within sight of our defenses.",
		],
		enemy_scouts: [
			"Enemy scouts at the perimeter! Activating defenses!",
			"Hostile reconnaissance near our walls. Engaging!",
			"Their scouts probe our defenses. They will find them solid.",
			"Enemy patrol at the boundary. Challenge issued.",
			"Scouts near the gate. They will not pass.",
			"Hostile eyes on our fortifications. Let them look.",
			"Enemy recon at the wall. Tracking their movement.",
			"Their scouts test our vigilance. We are awake.",
		],
		taking_fire: [
			"The perimeter is under fire! All stations alert!",
			"Taking fire on the wall! Holding position!",
			"They attack our defenses! We will not yield!",
			"Incoming fire! The fortifications absorb it!",
			"Under attack! The wall holds! So do we!",
			"Hostile fire on defensive positions! Returning fire!",
			"Breach attempt! Concentrating defenses!",
			"Fire on the perimeter! All units to battle stations!",
		],
		target_down: [
			"Intruder eliminated. The perimeter holds.",
			"Hostile down. Defense integrity maintained.",
			"Threat neutralized. No breach occurred.",
			"Target destroyed. The wall stands unbroken.",
			"Enemy eliminated at the boundary. Watch continues.",
			"One down. The rest will think twice.",
			"Perimeter secured. Hostile removed.",
			"Target down. Resuming standard patrol.",
		],
		storm_intensifying: [
			"Storm intensifying. Structural reinforcement engaged.",
			"Conditions worsening. The walls are built for this.",
			"Storm building. Patrol routes adjusted for safety.",
			"Heavy weather incoming. Fortifications holding.",
			"Storm escalation. Defensive systems weatherproofed.",
			"Getting rough. The perimeter takes the worst of it.",
			"Storm surge. Walls designed for this. Standing firm.",
			"Intensifying conditions. Guard posts secured.",
		],
		lightning_close: [
			"Lightning near the wall! Checking structural integrity!",
			"Close strike on the perimeter! Damage assessment!",
			"That bolt hit near the gate! Inspecting defenses!",
			"Lightning! The rods caught it. Systems normal.",
			"Strike at the wall! No breach. Fortifications hold.",
			"Close lightning! Perimeter rods doing their job.",
			"That hit near our position! All systems green.",
			"Lightning proximity! Defense grid undamaged.",
		],
	},
	feral: {
		hostile_construction: [
			"BUILDING. ENEMY BUILDING. DESTROY?",
			"SOMETHING NEW. ENEMY MAKES THING.",
			"CONSTRUCTION. NOISE. HATE NOISE.",
			"THEY BUILD. WE TEAR DOWN.",
			"NEW STRUCTURE. THREAT. SMASH?",
			"ENEMY BUILDING THING. BAD THING.",
			"CONSTRUCTION DETECTED. ANGRY.",
			"THEY MAKE. WE BREAK.",
		],
		enemy_scouts: [
			"INTRUDER! INTRUDER NEAR!",
			"SMELL ENEMY. CLOSE. VERY CLOSE.",
			"SCOUTS. SNEAKING. HATE SNEAKERS.",
			"ENEMY WATCHING. WATCHING US. ATTACK!",
			"HOSTILE NEARBY. TEETH READY.",
			"THEY CREEP. WE POUNCE.",
			"ENEMY SCOUT. WEAK. CRUSH.",
			"INTRUDER DETECTED. KILL MODE.",
		],
		taking_fire: [
			"HIT! HIT! RAGE!",
			"PAIN! THEY SHOOT! CHARGE!",
			"TAKING HITS! ANGRY! VERY ANGRY!",
			"FIRE! FIRE AT US! RETALIATE!",
			"HURT! MAKE THEM HURT MORE!",
			"DAMAGE! FUEL THE RAGE!",
			"THEY HIT US! UNFORGIVABLE!",
			"PAIN IS FUEL! ATTACK!",
		],
		target_down: [
			"DEAD. GOOD. NEXT.",
			"CRUSHED. SATISFYING.",
			"ENEMY DOWN. MORE?",
			"DESTROYED. WANT MORE.",
			"BROKEN. LIKE IT SHOULD BE.",
			"DEAD THING. MOVE ON.",
			"ELIMINATED. HUNGRY FOR MORE.",
			"DOWN. SEARCH FOR NEXT.",
		],
		storm_intensifying: [
			"STORM BIGGER. HIDE DEEPER.",
			"SKY ANGRIER. BAD BAD BAD.",
			"WORSE. GETTING WORSE. COWER.",
			"LIGHTNING MORE. SHELTER NOW.",
			"STORM GROWS. FEAR GROWS.",
			"BIG STORM. SMALL US.",
			"SKY RAGE INCREASING. RETREAT.",
			"MORE THUNDER. MORE DANGER.",
		],
		lightning_close: [
			"LIGHTNING! CLOSE! RUN!",
			"ZAP! NEAR! HIDE!",
			"BOOM! TOO CLOSE! COWER!",
			"ELECTRICITY! BURNING! FLEE!",
			"STRIKE NEAR! TERROR!",
			"LIGHTNING HIT CLOSE! PANIC!",
			"ZAP ZAP! SCARED! MOVE!",
			"BOLT! RIGHT THERE! AWAY AWAY!",
		],
	},
	cult: {
		hostile_construction: [
			"The heretics build their false temples. The EL sees all.",
			"Unholy construction. The EL will reclaim that ground.",
			"They build without divine sanction. It will crumble.",
			"Enemy construction. A blasphemy against the EL's design.",
			"The faithless erect structures. The storm will judge them.",
			"Heretic builders. Their work offends the cosmic order.",
			"They construct without prayer. It will not endure.",
			"False architecture. The EL's lightning will purify it.",
		],
		enemy_scouts: [
			"Heretic scouts near the sanctum! The EL warns us!",
			"Enemy eyes on holy ground. Blasphemy!",
			"Their scouts defile this space with observation.",
			"Hostile reconnaissance near the temple. Purge them.",
			"The faithless send spies. The EL sees them too.",
			"Enemy scouts. The divine signal reveals their position.",
			"Heretic patrol. The EL guides our counterattack.",
			"Their scouts will find only righteous fury here.",
		],
		taking_fire: [
			"The heretics attack! The EL shields the faithful!",
			"Under fire! The divine signal strengthens us!",
			"They shoot at the chosen! Blasphemy upon blasphemy!",
			"Taking fire! The EL's wrath will answer!",
			"Attack on the faithful! Lightning guide our defense!",
			"Incoming! The EL tests our devotion!",
			"Fire upon the holy! Righteous fury activated!",
			"They dare attack the EL's servants!",
		],
		target_down: [
			"The heretic falls. The EL is pleased.",
			"Purified by holy action. One less blasphemer.",
			"The faithless is destroyed. Divine justice served.",
			"Enemy down. The EL's will is done.",
			"Struck down. The cosmic order is restored.",
			"Heretic eliminated. The signal grows clearer.",
			"One less defiler. The EL blesses this victory.",
			"The unfaithful is purged. Praise the storm.",
		],
		storm_intensifying: [
			"The EL speaks louder! The storm is divine!",
			"Greater power! The EL's voice grows!",
			"The storm intensifies! The faithful rejoice!",
			"More lightning! More divine energy! Glorious!",
			"The EL's fury builds! We are blessed!",
			"Storm crescendo! The divine signal peaks!",
			"The heavens roar! The EL is near!",
			"Intensifying! The faithful feel the power!",
		],
		lightning_close: [
			"The EL reaches down! We are chosen!",
			"Divine lightning! The EL's finger touches this ground!",
			"Close strike! The EL's blessing! Beautiful!",
			"Lightning from the divine! We are in the EL's presence!",
			"The bolt of judgment! So close! So glorious!",
			"The EL's touch! Right here! Kneel!",
			"Holy lightning! The faithful are unafraid!",
			"Divine discharge! The EL communicates directly!",
		],
	},
};
