import type {
	CityFamily,
	CityPassabilityEffect,
	CityPlacementType,
	CityZone,
} from "./types";

export interface CityModelSemanticDefinition {
	family: CityFamily;
	placementType: CityPlacementType;
	footprint: {
		width: number;
		depth: number;
		height: number;
	};
	defaultScale: number;
	defaultRotation: number;
	rotationSymmetry: 1 | 2 | 4;
	pivotPolicy: string;
	passabilityEffect: CityPassabilityEffect;
	zoneAffinity: CityZone[];
	adjacencyBias: string[];
	compositeEligibility: string[];
	tags: string[];
}

function defineMany(
	ids: readonly string[],
	definition: CityModelSemanticDefinition,
) {
	return Object.fromEntries(ids.map((id) => [id, definition])) as Record<
		string,
		CityModelSemanticDefinition
	>;
}

const ALL_ZONES: CityZone[] = [
	"core",
	"power",
	"fabrication",
	"storage",
	"habitation",
	"corridor",
];

export const CITY_MODEL_SEMANTICS: Record<
	string,
	CityModelSemanticDefinition
> = {
	...defineMany(["column_1", "column_2"], {
		family: "column",
		placementType: "vertical",
		footprint: { width: 1, depth: 1, height: 4.5 },
		defaultScale: 0.92,
		defaultRotation: 0,
		rotationSymmetry: 4,
		pivotPolicy: "base_center",
		passabilityEffect: "blocking",
		zoneAffinity: ALL_ZONES,
		adjacencyBias: ["wall_edge", "room_corner", "gate_frame"],
		compositeEligibility: ["substation_core", "defensive_gate", "tower_stack"],
		tags: ["structural", "column", "support"],
	}),
	column_3: {
		family: "column",
		placementType: "vertical",
		footprint: { width: 1.5, depth: 1.5, height: 4.5 },
		defaultScale: 0.84,
		defaultRotation: 0,
		rotationSymmetry: 4,
		pivotPolicy: "base_center",
		passabilityEffect: "blocking",
		zoneAffinity: ALL_ZONES,
		adjacencyBias: ["wall_edge", "power_cluster", "tower_core"],
		compositeEligibility: ["substation_core", "archive_cluster", "cult_incursion_structure"],
		tags: ["structural", "column", "accent_column"],
	},
	column_slim: {
		family: "column",
		placementType: "vertical",
		footprint: { width: 1, depth: 1, height: 4.5 },
		defaultScale: 0.9,
		defaultRotation: 0,
		rotationSymmetry: 4,
		pivotPolicy: "base_center",
		passabilityEffect: "cover",
		zoneAffinity: ["corridor", "fabrication", "power", "storage"],
		adjacencyBias: ["utility_run", "corridor_edge", "transit_node"],
		compositeEligibility: ["relay_spine", "service_block", "power_sink_array"],
		tags: ["utility_column", "pipe_support"],
	},
	...defineMany(
		[
			"details_details_arrow",
			"details_details_arrow_2",
			"details_details_output",
			"details_details_output_small",
			"details_details_x",
			"details_details_dots",
			"details_details_hexagon",
			"details_details_triangles",
		],
		{
			family: "detail",
			placementType: "detail",
			footprint: { width: 1, depth: 0.2, height: 0.4 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 4,
			pivotPolicy: "surface_center",
			passabilityEffect: "guidance",
			zoneAffinity: ["corridor", "core", "power"],
			adjacencyBias: ["procedural_floor", "door_threshold", "transit_node"],
			compositeEligibility: ["relay_spine", "transit_node"],
			tags: ["signage", "guidance", "overlay"],
		},
	),
	...defineMany(
		[
			"details_details_basic_1",
			"details_details_basic_2",
			"details_details_basic_3",
			"details_details_basic_4",
			"details_details_plate_details",
			"details_details_plate_large",
			"details_details_plate_long",
			"details_details_plate_small",
		],
		{
			family: "detail",
			placementType: "detail",
			footprint: { width: 1, depth: 0.3, height: 0.6 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 4,
			pivotPolicy: "surface_center",
			passabilityEffect: "guidance",
			zoneAffinity: ["core", "fabrication", "storage", "corridor"],
			adjacencyBias: ["procedural_floor", "wall_base", "service_block"],
			compositeEligibility: ["service_block", "fabrication_hub", "storage_block"],
			tags: ["panel", "trim", "overlay"],
		},
	),
	...defineMany(
		[
			"details_details_cylinder",
			"details_details_cylinder_long",
			"details_details_pipes_long",
			"details_details_pipes_medium",
			"details_details_pipes_small",
			"details_details_vent_1",
			"details_details_vent_2",
			"details_details_vent_3",
			"details_details_vent_4",
			"details_details_vent_5",
		],
		{
			family: "detail",
			placementType: "detail",
			footprint: { width: 1, depth: 0.4, height: 0.6 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 4,
			pivotPolicy: "surface_center",
			passabilityEffect: "cover",
			zoneAffinity: ["power", "fabrication", "storage", "corridor"],
			adjacencyBias: ["roof_edge", "utility_spine", "power_sink_array"],
			compositeEligibility: ["power_sink_array", "relay_spine", "fabrication_hub", "service_block"],
			tags: ["pipework", "vent", "utility_detail"],
		},
	),
	door_double: {
		family: "door",
		placementType: "edge",
		footprint: { width: 2, depth: 0.5, height: 2.5 },
		defaultScale: 1,
		defaultRotation: 0,
		rotationSymmetry: 2,
		pivotPolicy: "edge_center",
		passabilityEffect: "portal",
		zoneAffinity: ["corridor", "core", "fabrication", "storage", "habitation", "power"],
		adjacencyBias: ["wall_edge", "transit_lane", "substation_core"],
		compositeEligibility: ["relay_spine", "transit_node", "defensive_gate"],
		tags: ["portal", "wide_door"],
	},
	door_single: {
		family: "door",
		placementType: "edge",
		footprint: { width: 1, depth: 0.5, height: 2.5 },
		defaultScale: 1,
		defaultRotation: 0,
		rotationSymmetry: 2,
		pivotPolicy: "edge_center",
		passabilityEffect: "portal",
		zoneAffinity: ["corridor", "habitation", "core", "storage"],
		adjacencyBias: ["wall_edge", "room_threshold"],
		compositeEligibility: ["substation_core", "archive_cluster", "tower_stack"],
		tags: ["portal", "single_door"],
	},
	...defineMany(
		[
			"floortile_basic",
			"floortile_basic2",
			"floortile_corner",
			"floortile_double_hallway",
			"floortile_empty",
			"floortile_innercorner",
			"floortile_side",
		],
		{
			family: "floor",
			placementType: "cell",
			footprint: { width: 2, depth: 2, height: 0.1 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 4,
			pivotPolicy: "surface_center",
			passabilityEffect: "walkable",
			zoneAffinity: ALL_ZONES,
			adjacencyBias: ["procedural_floor", "accent_floor"],
			compositeEligibility: [],
			tags: ["floor_accent", "optional_floor"],
		},
	),
	pipes: {
		family: "utility",
		placementType: "detail",
		footprint: { width: 2, depth: 1, height: 1 },
		defaultScale: 1,
		defaultRotation: 0,
		rotationSymmetry: 2,
		pivotPolicy: "surface_center",
		passabilityEffect: "cover",
		zoneAffinity: ["power", "fabrication", "corridor"],
		adjacencyBias: ["power_sink_array", "fabrication_hub", "relay_spine"],
		compositeEligibility: ["power_sink_array", "fabrication_hub"],
		tags: ["pipework", "utility_run"],
	},
	...defineMany(
		["props_base", "props_pod", "props_vessel", "props_vessel_short", "props_vessel_tall"],
		{
			family: "prop",
			placementType: "prop",
			footprint: { width: 1, depth: 1, height: 1.4 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 4,
			pivotPolicy: "base_center",
			passabilityEffect: "cover",
			zoneAffinity: ["storage", "fabrication", "power"],
			adjacencyBias: ["storage_block", "service_block", "motor_pool"],
			compositeEligibility: ["service_block", "storage_block", "motor_pool"],
			tags: ["equipment", "industrial_prop"],
		},
	),
	...defineMany(
		["props_computer", "props_computersmall", "props_statue"],
		{
			family: "prop",
			placementType: "prop",
			footprint: { width: 1, depth: 1, height: 1.2 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 4,
			pivotPolicy: "base_center",
			passabilityEffect: "cover",
			zoneAffinity: ["core", "fabrication", "habitation", "corridor"],
			adjacencyBias: ["substation_core", "archive_cluster", "fabrication_hub"],
			compositeEligibility: ["substation_core", "archive_cluster", "fabrication_hub"],
			tags: ["console", "operator_prop"],
		},
	),
	...defineMany(
		["props_containerfull", "props_crate", "props_cratelong", "props_chest", "props_shelf", "props_shelf_tall"],
		{
			family: "prop",
			placementType: "prop",
			footprint: { width: 1.2, depth: 1.2, height: 1.5 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 2,
			pivotPolicy: "base_center",
			passabilityEffect: "cover",
			zoneAffinity: ["storage", "fabrication", "corridor"],
			adjacencyBias: ["storage_block", "motor_pool", "transit_node"],
			compositeEligibility: ["storage_block", "service_block", "motor_pool", "transit_node"],
			tags: ["cargo", "storage_prop"],
		},
	),
	props_capsule: {
		family: "prop",
		placementType: "prop",
		footprint: { width: 1.4, depth: 1.4, height: 1.8 },
		defaultScale: 1,
		defaultRotation: 0,
		rotationSymmetry: 2,
		pivotPolicy: "base_center",
		passabilityEffect: "cover",
		zoneAffinity: ["power", "research", "habitation"] as CityZone[],
		adjacencyBias: ["cult_incursion_structure", "archive_cluster", "substation_core"],
		compositeEligibility: ["cult_incursion_structure", "archive_cluster"],
		tags: ["capsule", "ritual_or_pod"],
	},
	props_laser: {
		family: "prop",
		placementType: "prop",
		footprint: { width: 1, depth: 1, height: 1.2 },
		defaultScale: 1,
		defaultRotation: 0,
		rotationSymmetry: 4,
		pivotPolicy: "base_center",
		passabilityEffect: "cover",
		zoneAffinity: ["power", "corridor", "core"],
		adjacencyBias: ["defensive_gate", "power_sink_array"],
		compositeEligibility: ["defensive_gate"],
		tags: ["weapon", "defense_prop"],
	},
	...defineMany(["props_teleporter_1", "props_teleporter_2"], {
		family: "utility",
		placementType: "prop",
		footprint: { width: 1.4, depth: 1.4, height: 1.6 },
		defaultScale: 1,
		defaultRotation: 0,
		rotationSymmetry: 4,
		pivotPolicy: "base_center",
		passabilityEffect: "portal",
		zoneAffinity: ["core", "power", "corridor", "fabrication"],
		adjacencyBias: ["relay_spine", "transit_node", "power_sink_array"],
		compositeEligibility: ["relay_spine", "transit_node", "power_sink_array", "substation_core"],
		tags: ["teleport", "transit", "relay"],
	}),
	...defineMany(
		[
			"rooftile_corner_pipes",
			"rooftile_details",
			"rooftile_empty",
			"rooftile_innercorner_pipes",
			"rooftile_orangevent",
			"rooftile_pipes1",
			"rooftile_pipes2",
			"rooftile_plate",
			"rooftile_plate2",
			"rooftile_sides_pipes",
			"rooftile_smallvents",
			"rooftile_vents",
		],
		{
			family: "roof",
			placementType: "roof",
			footprint: { width: 2, depth: 2, height: 0.5 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 4,
			pivotPolicy: "top_center",
			passabilityEffect: "blocking",
			zoneAffinity: ALL_ZONES,
			adjacencyBias: ["roofline", "sealed_room", "service_block"],
			compositeEligibility: [
				"substation_core",
				"tower_stack",
				"relay_spine",
				"service_block",
				"storage_block",
				"fabrication_hub",
				"archive_cluster",
				"defensive_gate",
				"power_sink_array",
			],
			tags: ["roof", "cap", "weather_shell"],
		},
	),
	staircase: {
		family: "stair",
		placementType: "vertical",
		footprint: { width: 2, depth: 2, height: 2.4 },
		defaultScale: 1,
		defaultRotation: 0,
		rotationSymmetry: 4,
		pivotPolicy: "base_center",
		passabilityEffect: "vertical_connector",
		zoneAffinity: ["core", "habitation", "power", "corridor"],
		adjacencyBias: ["tower_core", "archive_cluster", "tower_stack"],
		compositeEligibility: ["tower_stack", "archive_cluster"],
		tags: ["stairs", "vertical_circulation"],
	},
	...defineMany(
		[
			"walls_doordoublelong_wall_sidea",
			"walls_doordouble_wall_sidea",
			"walls_doordouble_wall_sideb",
			"walls_doorsinglelong_wall_sidea",
			"walls_doorsingle_wall_sidea",
			"walls_doorsingle_wall_sideb",
		],
		{
			family: "door",
			placementType: "edge",
			footprint: { width: 2, depth: 0.5, height: 2.8 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 2,
			pivotPolicy: "edge_center",
			passabilityEffect: "portal",
			zoneAffinity: ["corridor", "core", "fabrication", "storage", "habitation", "power"],
			adjacencyBias: ["wall_edge", "door_frame", "sealed_room"],
			compositeEligibility: [
				"substation_core",
				"tower_stack",
				"relay_spine",
				"service_block",
				"storage_block",
				"fabrication_hub",
				"defensive_gate",
				"transit_node",
				"archive_cluster",
			],
			tags: ["wall_door", "portal_frame"],
		},
	),
	...defineMany(
		[
			"walls_longwindow_wall_sidea",
			"walls_longwindow_wall_sideb",
			"walls_smallwindows_wall_sidea",
			"walls_smallwindows_wall_sideb",
			"walls_threewindows_wall_sidea",
			"walls_threewindows_wall_sideb",
			"walls_window_wall_sidea",
			"walls_window_wall_sideb",
		],
		{
			family: "wall",
			placementType: "edge",
			footprint: { width: 2, depth: 0.5, height: 2.8 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 2,
			pivotPolicy: "edge_center",
			passabilityEffect: "blocking",
			zoneAffinity: ["core", "habitation", "power", "corridor"],
			adjacencyBias: ["wall_edge", "window_run", "room_perimeter"],
			compositeEligibility: [
				"substation_core",
				"tower_stack",
				"archive_cluster",
				"service_block",
			],
			tags: ["wall", "window_wall", "perimeter"],
		},
	),
	...defineMany(
		[
			"walls_wall_1",
			"walls_wall_2",
			"walls_wall_3",
			"walls_wall_4",
			"walls_wall_5",
			"walls_wall_empty",
		],
		{
			family: "wall",
			placementType: "edge",
			footprint: { width: 2, depth: 0.5, height: 2.8 },
			defaultScale: 1,
			defaultRotation: 0,
			rotationSymmetry: 2,
			pivotPolicy: "edge_center",
			passabilityEffect: "blocking",
			zoneAffinity: ALL_ZONES,
			adjacencyBias: ["wall_edge", "sealed_room", "corridor_run"],
			compositeEligibility: [
				"substation_core",
				"tower_stack",
				"relay_spine",
				"service_block",
				"storage_block",
				"fabrication_hub",
				"defensive_gate",
				"transit_node",
				"archive_cluster",
				"cult_incursion_structure",
			],
			tags: ["wall", "perimeter", "structural_shell"],
		},
	),
};
