/**
 * Power system -- lightning rods capture storm energy and distribute it.
 *
 * Power flows from lightning rods to connected buildings/units via BFS.
 * Buildings within a rod's protection radius receive power.
 * Units can charge when near a powered building.
 *
 * Storm intensity affects rod output (fluctuates over time).
 */

import {
	BuildingTrait,
	LightningRod,
	Navigation,
	Position,
	Unit,
} from "../ecs/traits";
import { world } from "../ecs/world";

/** How far power reaches from a lightning rod */
const DEFAULT_POWER_RADIUS = 12;

/** Storm intensity oscillates -- affects all rod output */
let stormIntensity = 1.0;
let stormPhase = 0;

/**
 * Update storm intensity. Called each sim tick.
 * The storm fluctuates with slow waves, occasionally surging.
 */
function updateStormIntensity(tick: number) {
	stormPhase = tick * 0.02;
	// Base oscillation (slow sine wave)
	const base = 0.7 + 0.2 * Math.sin(stormPhase * 0.3);
	// Occasional surges
	const surge = Math.max(0, Math.sin(stormPhase * 1.7 + 2.3)) * 0.3;
	stormIntensity = Math.min(1.5, base + surge);
}

export function getStormIntensity(): number {
	return stormIntensity;
}

/**
 * Calculate total power generated by all lightning rods.
 */
function getTotalPowerGeneration(): number {
	let total = 0;
	for (const rod of world.query(LightningRod, BuildingTrait, Position)) {
		const lr = rod.get(LightningRod)!;
		const output = lr.rodCapacity * stormIntensity;
		rod.set(LightningRod, { currentOutput: output });
		total += output;
	}
	return total;
}

/**
 * Calculate total power demanded by all buildings and units.
 */
function getTotalPowerDemand(): number {
	let demand = 0;
	for (const building of world.query(BuildingTrait, Position)) {
		const bldg = building.get(BuildingTrait)!;
		if (bldg.operational) {
			demand += getBuildingPowerDemand(bldg.buildingType);
		}
	}
	for (const unit of world.query(Unit, Position)) {
		const u = unit.get(Unit)!;
		// Skip fabrication units -- their demand is counted via building component
		if (u.unitType === "fabrication_unit") continue;
		const nav = unit.has(Navigation) ? unit.get(Navigation)! : null;
		demand += getUnitPowerDemand(nav?.moving ?? false);
	}
	return demand;
}

function getBuildingPowerDemand(buildingType: string): number {
	switch (buildingType) {
		case "fabrication_unit":
			return 3;
		case "lightning_rod":
			return 0; // generates, doesn't consume
		default:
			return 1;
	}
}

function getUnitPowerDemand(isMoving: boolean): number {
	// Moving units consume more
	const baseDemand = 0.5;
	const movingBonus = isMoving ? 0.3 : 0;
	return baseDemand + movingBonus;
}

/**
 * Distribute power: buildings within rod range get powered.
 * If total generation < total demand, some buildings lose power.
 */
function distributePower() {
	// First, mark all non-rod buildings as unpowered
	for (const building of world.query(BuildingTrait, Position)) {
		const bldg = building.get(BuildingTrait)!;
		if (bldg.buildingType !== "lightning_rod") {
			building.set(BuildingTrait, { powered: false });
		}
	}

	// For each rod, power nearby buildings
	for (const rod of world.query(LightningRod, BuildingTrait, Position)) {
		const lr = rod.get(LightningRod)!;
		const radius = lr.protectionRadius || DEFAULT_POWER_RADIUS;
		const rodPos = rod.get(Position)!;

		for (const building of world.query(BuildingTrait, Position)) {
			const bldg = building.get(BuildingTrait)!;
			if (bldg.buildingType === "lightning_rod") continue;

			const bldgPos = building.get(Position)!;
			const dx = bldgPos.x - rodPos.x;
			const dz = bldgPos.z - rodPos.z;
			const dist = Math.sqrt(dx * dx + dz * dz);

			if (dist <= radius) {
				building.set(BuildingTrait, { powered: true, operational: true });
			}
		}
	}
}

export interface PowerSnapshot {
	totalGeneration: number;
	totalDemand: number;
	stormIntensity: number;
	rodCount: number;
	poweredBuildingCount: number;
}

let lastPowerSnapshot: PowerSnapshot = {
	totalGeneration: 0,
	totalDemand: 0,
	stormIntensity: 1.0,
	rodCount: 0,
	poweredBuildingCount: 0,
};

export function getPowerSnapshot(): PowerSnapshot {
	return lastPowerSnapshot;
}

/**
 * Run power system. Called once per sim tick.
 */
export function powerSystem(tick: number) {
	updateStormIntensity(tick);
	const generation = getTotalPowerGeneration();
	const demand = getTotalPowerDemand();
	distributePower();

	let poweredCount = 0;
	for (const building of world.query(BuildingTrait, Position)) {
		if (building.get(BuildingTrait)?.powered) poweredCount++;
	}

	const rodCount = Array.from(
		world.query(LightningRod, BuildingTrait, Position),
	).length;

	lastPowerSnapshot = {
		totalGeneration: Math.round(generation * 10) / 10,
		totalDemand: Math.round(demand * 10) / 10,
		stormIntensity: Math.round(stormIntensity * 100) / 100,
		rodCount,
		poweredBuildingCount: poweredCount,
	};
}
