import buildingsConfig from "../config/buildings.json";
import gameplayConfig from "../config/gameplay.json";
import unitsConfig from "../config/units.json";
import type { BuildingEntity, Entity } from "../ecs/traits";
import {
	Building,
	LightningRod,
	Navigation,
	Unit,
	WorldPosition,
} from "../ecs/traits";
import { buildings, lightningRods, units } from "../ecs/world";

/**
 * Power system — lightning rods capture storm energy and distribute it.
 *
 * Power flows from lightning rods to connected buildings/units via BFS.
 * Buildings within a rod's protection radius receive power.
 * Units can charge when near a powered building.
 *
 * Storm intensity affects rod output (fluctuates over time).
 */

/** Storm intensity oscillates — affects all rod output */
let stormIntensity = 1.0;
let stormPhase = 0;

/**
 * Update storm intensity. Called each sim tick.
 * The storm fluctuates with slow waves, occasionally surging.
 */
function updateStormIntensity(tick: number) {
	stormPhase = tick * 0.02;
	const { baseStormIntensity, stormOscillation, stormSurgeMax } =
		gameplayConfig.power;
	// Base oscillation (slow sine wave)
	const base =
		baseStormIntensity + stormOscillation * Math.sin(stormPhase * 0.3);
	// Occasional surges
	const surge = Math.max(0, Math.sin(stormPhase * 1.7 + 2.3)) * stormSurgeMax;
	stormIntensity = Math.min(1.5, base + surge);
}

export function getStormIntensity(): number {
	return stormIntensity;
}

/**
 * Calculate total power generated by all lightning rods.
 */
function getTotalPowerGeneration(): number {
	let total = 0;
	for (const rod of lightningRods) {
		const output = rod.get(LightningRod)?.rodCapacity * stormIntensity;
		rod.get(LightningRod)!.currentOutput = output;
		total += output;
	}
	return total;
}

/**
 * Calculate total power demanded by all buildings and units.
 */
function getTotalPowerDemand(): number {
	let demand = 0;
	for (const building of buildings) {
		if (building.get(Building)?.operational) {
			demand += getBuildingPowerDemand(building);
		}
	}
	for (const unit of units) {
		// Skip fabrication units — their demand is counted via building component
		if (unit.get(Unit)?.type === "fabrication_unit") continue;
		demand += getUnitPowerDemand(unit as any);
	}
	return demand;
}

function getBuildingPowerDemand(entity: BuildingEntity): number {
	const type = entity.get(Building)?.type as keyof typeof buildingsConfig;
	return buildingsConfig[type]?.powerDemand ?? 0;
}

function getUnitPowerDemand(entity: Entity): number {
	const type = entity.get(Unit)?.type as keyof typeof unitsConfig;
	const config = unitsConfig[type];
	if (!config) return 0;

	const baseDemand = config.powerDemand;
	const movingBonus = entity.get(Navigation)?.moving
		? config.movingPowerBonus
		: 0;
	return baseDemand + movingBonus;
}

/**
 * Distribute power: buildings within rod range get powered.
 * If total generation < total demand, some buildings lose power.
 */
function distributePower() {
	// First, mark all buildings as unpowered
	for (const building of buildings) {
		if (building.get(Building)?.type !== "lightning_rod") {
			building.get(Building)!.powered = false;
		}
	}

	// For each rod, power nearby buildings
	for (const rod of lightningRods) {
		const radius =
			rod.get(LightningRod)?.protectionRadius ||
			gameplayConfig.power.defaultRadius;
		const rx = rod.get(WorldPosition)?.x;
		const rz = rod.get(WorldPosition)?.z;

		for (const building of buildings) {
			if (building.get(Building)?.type === "lightning_rod") continue;

			const dx = building.get(WorldPosition)?.x - rx;
			const dz = building.get(WorldPosition)?.z - rz;
			const dist = Math.sqrt(dx * dx + dz * dz);

			if (dist <= radius) {
				building.get(Building)!.powered = true;
				building.get(Building)!.operational = true;
			}
		}
	}
}

export interface PowerSnapshot {
	totalGeneration: number;
	totalDemand: number;
	stormIntensity: number;
	rodCount: number;
	poweredBuildingCount: number;
}

let lastPowerSnapshot: PowerSnapshot = {
	totalGeneration: 0,
	totalDemand: 0,
	stormIntensity: 1.0,
	rodCount: 0,
	poweredBuildingCount: 0,
};

export function getPowerSnapshot(): PowerSnapshot {
	return lastPowerSnapshot;
}

/**
 * Run power system. Called once per sim tick.
 */
export function powerSystem(tick: number) {
	updateStormIntensity(tick);
	const generation = getTotalPowerGeneration();
	const demand = getTotalPowerDemand();
	distributePower();

	let poweredCount = 0;
	for (const building of buildings) {
		if (building.get(Building)?.powered) poweredCount++;
	}

	lastPowerSnapshot = {
		totalGeneration: Math.round(generation * 10) / 10,
		totalDemand: Math.round(demand * 10) / 10,
		stormIntensity: Math.round(stormIntensity * 100) / 100,
		rodCount: Array.from(lightningRods).length,
		poweredBuildingCount: poweredCount,
	};
}
