/**
 * Faction-buildable structure definitions.
 *
 * Power model: the perpetual storm IS the power grid.
 * Storm transmitters tap it, power boxes store the charge,
 * everything else draws from nearby power boxes.
 *
 * Ported from: pending/config/buildings.json + modelDefinitions.json
 * GLB models: public/assets/models/
 */

import type { ResourceMaterial } from "../terrain/types";
import type { BuildingType } from "../traits/building";

export interface BuildingDef {
	readonly displayName: string;
	readonly modelId: string;
	readonly assetPath: string;
	readonly hp: number;
	readonly powerDelta: number;
	readonly powerRadius: number;
	readonly storageCapacity: number;
	readonly signalRange: number;
	readonly signalStrength: number;
	readonly fabricationSlots: number;
	readonly turretDamage: number;
	readonly turretRange: number;
	readonly turretCooldown: number;
	readonly buildCost: Partial<Record<ResourceMaterial, number>>;
	readonly buildTime: number;
}

export const BUILDING_DEFS: Record<BuildingType, BuildingDef> = {
	storm_transmitter: {
		displayName: "Storm Transmitter",
		modelId: "antenna_1",
		assetPath: "infrastructure/Antenna_1.glb",
		hp: 40,
		powerDelta: 5,
		powerRadius: 12,
		storageCapacity: 0,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { ferrous_scrap: 3, conductor_wire: 2 },
		buildTime: 4,
	},
	power_box: {
		displayName: "Power Box",
		modelId: "power_box_01",
		assetPath: "infrastructure/power_box_01.glb",
		hp: 30,
		powerDelta: 0,
		powerRadius: 0,
		storageCapacity: 20,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { ferrous_scrap: 2, conductor_wire: 1 },
		buildTime: 2,
	},
	synthesizer: {
		displayName: "Synthesizer",
		modelId: "machine_generator_large",
		assetPath: "infrastructure/machine_generatorLarge.glb",
		hp: 60,
		powerDelta: -4,
		powerRadius: 0,
		storageCapacity: 0,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { alloy_stock: 4, silicon_wafer: 2, conductor_wire: 2 },
		buildTime: 8,
	},
	motor_pool: {
		displayName: "Motor Pool",
		modelId: "machine_building_plant",
		assetPath: "buildings/Machine_building_plant.glb",
		hp: 80,
		powerDelta: -3,
		powerRadius: 0,
		storageCapacity: 0,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 1,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { ferrous_scrap: 6, alloy_stock: 3, silicon_wafer: 1 },
		buildTime: 10,
	},
	relay_tower: {
		displayName: "Relay Tower",
		modelId: "satellite_dish",
		assetPath: "infrastructure/satelliteDish.glb",
		hp: 35,
		powerDelta: -1,
		powerRadius: 0,
		storageCapacity: 0,
		signalRange: 10,
		signalStrength: 1.0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { conductor_wire: 3, silicon_wafer: 1 },
		buildTime: 4,
	},
	defense_turret: {
		displayName: "Defense Turret",
		modelId: "turret_cannon",
		assetPath: "defense/Turret_Cannon.glb",
		hp: 50,
		powerDelta: -2,
		powerRadius: 0,
		storageCapacity: 0,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 3,
		turretRange: 8,
		turretCooldown: 2,
		buildCost: { ferrous_scrap: 4, alloy_stock: 2, silicon_wafer: 1 },
		buildTime: 6,
	},
	storage_hub: {
		displayName: "Storage Hub",
		modelId: "resource_warehouse",
		assetPath: "buildings/Resource_warehouse.glb",
		hp: 40,
		powerDelta: 0,
		powerRadius: 0,
		storageCapacity: 50,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { ferrous_scrap: 3, polymer_salvage: 2 },
		buildTime: 3,
	},
	maintenance_bay: {
		displayName: "Maintenance Bay",
		modelId: "robot_arm_a",
		assetPath: "industrial/robot-arm-a.glb",
		hp: 45,
		powerDelta: -2,
		powerRadius: 0,
		storageCapacity: 0,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { alloy_stock: 3, conductor_wire: 2, silicon_wafer: 1 },
		buildTime: 6,
	},
	power_plant: {
		displayName: "Power Plant",
		modelId: "reactor",
		assetPath: "buildings/Reactor.glb",
		hp: 120,
		powerDelta: 10,
		powerRadius: 20,
		storageCapacity: 0,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: {
			alloy_stock: 8,
			silicon_wafer: 4,
			conductor_wire: 3,
			el_crystal: 1,
		},
		buildTime: 16,
	},
	research_lab: {
		displayName: "Research Lab",
		modelId: "research_center",
		assetPath: "buildings/Research_center.glb",
		hp: 80,
		powerDelta: -5,
		powerRadius: 0,
		storageCapacity: 0,
		signalRange: 15,
		signalStrength: 2.0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { alloy_stock: 6, silicon_wafer: 4, conductor_wire: 2 },
		buildTime: 12,
	},
	resource_refinery: {
		displayName: "Resource Refinery",
		modelId: "machine_generator_large",
		assetPath: "infrastructure/machine_generatorLarge.glb",
		hp: 70,
		powerDelta: -3,
		powerRadius: 0,
		storageCapacity: 40,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { polymer_salvage: 4, alloy_stock: 3, conductor_wire: 2 },
		buildTime: 8,
	},
	solar_array: {
		displayName: "Solar Array",
		modelId: "solar_generator",
		assetPath: "buildings/Solar_generator.glb",
		hp: 25,
		powerDelta: 3,
		powerRadius: 8,
		storageCapacity: 0,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { silicon_wafer: 3, conductor_wire: 2 },
		buildTime: 4,
	},
	geothermal_tap: {
		displayName: "Geothermal Tap",
		modelId: "geothermal_generator",
		assetPath: "buildings/Geothermal_generator.glb",
		hp: 50,
		powerDelta: 7,
		powerRadius: 15,
		storageCapacity: 0,
		signalRange: 0,
		signalStrength: 0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { alloy_stock: 5, ferrous_scrap: 4, thermal_fluid: 2 },
		buildTime: 10,
	},
	outpost: {
		displayName: "Outpost Module",
		modelId: "basemodule_a",
		assetPath: "buildings/basemodule_A.glb",
		hp: 40,
		powerDelta: -1,
		powerRadius: 0,
		storageCapacity: 15,
		signalRange: 5,
		signalStrength: 0.5,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: { ferrous_scrap: 4, alloy_stock: 2 },
		buildTime: 5,
	},
	wormhole_stabilizer: {
		displayName: "Wormhole Stabilizer",
		modelId: "props_teleporter_2",
		assetPath: "city/Props_Teleporter_2.glb",
		hp: 200,
		powerDelta: -15,
		powerRadius: 0,
		storageCapacity: 0,
		signalRange: 30,
		signalStrength: 5.0,
		fabricationSlots: 0,
		turretDamage: 0,
		turretRange: 0,
		turretCooldown: 0,
		buildCost: {
			intact_components: 50,
			storm_charge: 30,
			silicon_wafer: 25,
			alloy_stock: 25,
			el_crystal: 10,
		},
		buildTime: 20,
	},
} as const;
