/**
 * Power routing system — BFS power distribution through wire graphs.
 *
 * Power flows from lightning rods (sources) through wire connections to
 * consumer buildings (miners, fabrication units, processors). Power
 * diminishes over distance based on config/power.json loss rates.
 *
 * This system replaces the radius-based power distribution in power.ts
 * with wire-graph routing. Buildings must be physically wired to receive power.
 *
 * Runs each simulation tick after the power system updates rod outputs.
 */

import { config } from "../../config";
import type { Entity } from "../ecs/types";
import {
	buildings,
	lightningRods,
	miners,
	processors,
	wires,
	world,
} from "../ecs/world";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Power allocation record for a single entity */
export interface PowerAllocation {
	entityId: string;
	/** Power received at this entity after wire losses */
	received: number;
	/** Power demanded by this entity */
	demand: number;
	/** Whether demand is fully satisfied */
	satisfied: boolean;
	/** Distance in wire segments from nearest power source */
	hops: number;
}

/** Snapshot of the entire power grid state */
export interface PowerGridSnapshot {
	/** Total power generated by all lightning rods */
	totalGeneration: number;
	/** Total power demanded by all connected consumers */
	totalDemand: number;
	/** Total power surplus (generation - demand), can be negative */
	surplus: number;
	/** Per-entity power allocations */
	allocations: Map<string, PowerAllocation>;
	/** Set of entity IDs that are receiving power */
	poweredEntityIds: Set<string>;
	/** Per-wire power flow (wireEntityId -> absolute flow value) */
	wireFlows: Map<string, number>;
}

// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

let gridSnapshot: PowerGridSnapshot = {
	totalGeneration: 0,
	totalDemand: 0,
	surplus: 0,
	allocations: new Map(),
	poweredEntityIds: new Set(),
	wireFlows: new Map(),
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getEntityById(id: string): Entity | undefined {
	for (const entity of world) {
		if (entity.id === id) return entity;
	}
	return undefined;
}

/**
 * Get the power demand for a building based on its type.
 * Uses config/buildings.json where available, with sensible defaults.
 */
function getEntityPowerDemand(entity: Entity): number {
	if (entity.lightningRod) return 0; // generators don't consume

	const buildingType = entity.building?.type;
	if (!buildingType) return 0;

	const buildingConfig = (config.buildings as Record<string, { powerRequired?: number }>)[
		buildingType
	];
	if (buildingConfig?.powerRequired !== undefined) {
		return buildingConfig.powerRequired;
	}

	// Default demands by type
	switch (buildingType) {
		case "fabrication_unit":
			return 3;
		case "miner":
			return 2;
		default:
			return 1;
	}
}

// ---------------------------------------------------------------------------
// Wire graph construction
// ---------------------------------------------------------------------------

interface WireEdge {
	neighborId: string;
	wireEntity: Entity;
	wireLength: number;
}

/**
 * Build a bidirectional adjacency list from power wire entities.
 * Returns a map from entityId to list of connected neighbors with wire metadata.
 */
function buildPowerWireGraph(): Map<string, WireEdge[]> {
	const graph = new Map<string, WireEdge[]>();

	for (const wireEntity of wires) {
		if (wireEntity.wire.wireType !== "power") continue;

		const fromId = wireEntity.wire.fromEntityId;
		const toId = wireEntity.wire.toEntityId;

		if (!graph.has(fromId)) graph.set(fromId, []);
		if (!graph.has(toId)) graph.set(toId, []);

		graph.get(fromId)!.push({
			neighborId: toId,
			wireEntity,
			wireLength: wireEntity.wire.length,
		});
		graph.get(toId)!.push({
			neighborId: fromId,
			wireEntity,
			wireLength: wireEntity.wire.length,
		});
	}

	return graph;
}

// ---------------------------------------------------------------------------
// BFS power distribution
// ---------------------------------------------------------------------------

/**
 * Run BFS from all lightning rod sources through the power wire graph.
 *
 * Algorithm:
 * 1. Collect all lightning rods as power sources with their currentOutput.
 * 2. BFS outward through power wires, distributing power evenly at each fork.
 * 3. Power diminishes by wireLossPerUnit * wireLength at each wire segment.
 * 4. Each consumer entity records the max power it receives from any path.
 * 5. If received power >= demand, the entity is marked as powered.
 */
function distributePowerBFS(): PowerGridSnapshot {
	const { wireLossPerUnit, wireMaxCapacity } = config.power;

	const allocations = new Map<string, PowerAllocation>();
	const poweredEntityIds = new Set<string>();
	const wireFlows = new Map<string, number>();

	// Reset all power wire loads
	for (const wireEntity of wires) {
		if (wireEntity.wire.wireType === "power") {
			wireEntity.wire.currentLoad = 0;
		}
	}

	const graph = buildPowerWireGraph();

	// Calculate total generation
	let totalGeneration = 0;
	for (const rod of lightningRods) {
		totalGeneration += rod.lightningRod.currentOutput;
		poweredEntityIds.add(rod.id);

		// Lightning rods are always self-powered
		allocations.set(rod.id, {
			entityId: rod.id,
			received: rod.lightningRod.currentOutput,
			demand: 0,
			satisfied: true,
			hops: 0,
		});
	}

	if (graph.size === 0) {
		return {
			totalGeneration,
			totalDemand: 0,
			surplus: totalGeneration,
			allocations,
			poweredEntityIds,
			wireFlows,
		};
	}

	// BFS queue: { entityId, availablePower, hops }
	const visited = new Set<string>();
	const queue: {
		entityId: string;
		availablePower: number;
		hops: number;
	}[] = [];

	// Seed BFS from each lightning rod
	for (const rod of lightningRods) {
		if (!graph.has(rod.id)) continue;
		queue.push({
			entityId: rod.id,
			availablePower: rod.lightningRod.currentOutput,
			hops: 0,
		});
		visited.add(rod.id);
	}

	let head = 0;
	while (head < queue.length) {
		const current = queue[head++];
		const neighbors = graph.get(current.entityId);
		if (!neighbors) continue;

		// Filter to unvisited neighbors
		const unvisited = neighbors.filter((n) => !visited.has(n.neighborId));
		if (unvisited.length === 0) continue;

		// Distribute available power evenly across unvisited neighbors
		const powerPerBranch = current.availablePower / unvisited.length;

		for (const { neighborId, wireEntity, wireLength } of unvisited) {
			visited.add(neighborId);

			// Wire capacity limits flow
			const capacityLimit = wireEntity.wire.maxCapacity || wireMaxCapacity;
			const flow = Math.min(powerPerBranch, capacityLimit);

			// Power loss over wire length
			const loss = wireLossPerUnit * wireLength;
			const delivered = Math.max(0, flow * (1 - loss));

			// Track wire flow
			const existingFlow = wireFlows.get(wireEntity.id) ?? 0;
			wireFlows.set(wireEntity.id, existingFlow + flow);

			// Update wire load ratio (currentLoad = flow / maxCapacity, clamped 0..1)
			wireEntity.wire.currentLoad = Math.min(
				1,
				(existingFlow + flow) / capacityLimit,
			);

			const hops = current.hops + 1;

			// Record allocation for this entity
			const neighborEntity = getEntityById(neighborId);
			if (neighborEntity) {
				const demand = getEntityPowerDemand(neighborEntity);
				const existing = allocations.get(neighborId);

				// Take the best power delivery (in case multiple paths reach this entity)
				const bestReceived = Math.max(existing?.received ?? 0, delivered);
				const satisfied = bestReceived >= demand * 0.9; // 90% threshold

				allocations.set(neighborId, {
					entityId: neighborId,
					received: bestReceived,
					demand,
					satisfied,
					hops: existing ? Math.min(existing.hops, hops) : hops,
				});

				if (delivered > 0.1) {
					poweredEntityIds.add(neighborId);
				}
			}

			// Continue BFS if meaningful power remains after this wire
			if (delivered > 0.05) {
				queue.push({
					entityId: neighborId,
					availablePower: delivered,
					hops,
				});
			}
		}
	}

	// Calculate total demand
	let totalDemand = 0;
	for (const [, alloc] of allocations) {
		totalDemand += alloc.demand;
	}

	return {
		totalGeneration,
		totalDemand,
		surplus: totalGeneration - totalDemand,
		allocations,
		poweredEntityIds,
		wireFlows,
	};
}

// ---------------------------------------------------------------------------
// Apply power state to buildings
// ---------------------------------------------------------------------------

/**
 * Update building powered/operational flags based on wire-routed power.
 */
function applyPowerToBuildings(snapshot: PowerGridSnapshot) {
	// First, mark all non-rod buildings as unpowered
	for (const building of buildings) {
		if (building.building.type === "lightning_rod") continue;
		building.building.powered = false;
	}

	// Apply wire-routed power
	for (const building of buildings) {
		if (building.building.type === "lightning_rod") continue;

		if (snapshot.poweredEntityIds.has(building.id)) {
			const alloc = snapshot.allocations.get(building.id);
			if (alloc && alloc.satisfied) {
				building.building.powered = true;
				building.building.operational = true;
			}
		}
	}

	// Also power miners and processors if they have building components
	for (const miner of miners) {
		if (snapshot.poweredEntityIds.has(miner.id)) {
			const alloc = snapshot.allocations.get(miner.id);
			if (alloc && alloc.satisfied) {
				miner.building.powered = true;
				miner.building.operational = true;
			}
		}
	}

	for (const proc of processors) {
		if (snapshot.poweredEntityIds.has(proc.id)) {
			const alloc = snapshot.allocations.get(proc.id);
			if (alloc && alloc.satisfied) {
				proc.building.powered = true;
				proc.building.operational = true;
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Run the power routing system. Called once per simulation tick,
 * after power.ts updates rod outputs and storm intensity.
 */
export function updatePowerGrid() {
	gridSnapshot = distributePowerBFS();
	applyPowerToBuildings(gridSnapshot);
}

/**
 * Get the power received at a specific entity.
 * Returns 0 if the entity is not connected to any power source.
 */
export function getPowerAtEntity(entityId: string): number {
	const alloc = gridSnapshot.allocations.get(entityId);
	return alloc?.received ?? 0;
}

/**
 * Check if an entity is receiving power through the wire network.
 */
export function isPowered(entityId: string): boolean {
	return gridSnapshot.poweredEntityIds.has(entityId);
}

/**
 * Get the full power grid snapshot for UI display.
 */
export function getPowerGridSnapshot(): PowerGridSnapshot {
	return gridSnapshot;
}

/**
 * Get the power flow through a specific wire entity.
 * Returns 0 if the wire is not carrying power.
 */
export function getWireFlow(wireEntityId: string): number {
	return gridSnapshot.wireFlows.get(wireEntityId) ?? 0;
}
